#Logging
logging:
  level:
    org.springframework: INFO
    com.zacharyhuang: INFO
  pattern:
    console: "%d{dd-MM-yyyy HH:mm:ss.SSS} %magenta([%thread]) %highlight(%-5level) %logger{36} - %msg [%mdc]%n"

spring:
  profiles:
    active: "dev"
  main:
    banner-mode: "off"
